services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: kyna-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - kyna-network

  # Kyna API Backend
  kyna-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: kyna-api
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    networks:
      - kyna-network
    command: uvicorn kyna.api.main:app --host 0.0.0.0 --port 8000

  # Kyna Streamlit Playground
  kyna-playground:
    build:
      context: .
      dockerfile: Dockerfile.playground
    container_name: kyna-playground
    ports:
      - "8501:8501"
    depends_on:
      - kyna-api
    environment:
      - API_BASE_URL=http://kyna-api:8000/api
    volumes:
      - ./config:/app/config
    networks:
      - kyna-network
    command: streamlit run kyna/playground/app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  qdrant_data:

networks:
  kyna-network:
    driver: bridge